name: Dmidecode Info Test
description: This test prints out the output of dmidecode.

defaults:
  hwaas: &hwaas_parameter
    host: "[[.HwaaSHost]]"
    context_id: "[[.ContextID]]"
    device_id: "[[.DeviceID]]"
    machine_id: "[[.MachineID]]"
    version: "[[.Version]]"
    image: "[[.DefaultImage]]"

  transport: &transport
    proto: ssh
    options:
      host: "[[.Host]]"
      user: root
      identity_file: /root/.ssh/fwci

stages:
  - name: Pre-Requirement
    steps:
      - cmd: hwaas
        name: Read backup image from flash; ASdAsdASDa
        parameters:
          <<: *hwaas_parameter
          command: flash
          args: [read, /tmp/oldfirmware.bin]

      - cmd: hwaas
        name: Flash binary
        options:
          timeout: 60m
        parameters:
          <<: *hwaas_parameter
          command: flash
          args: [write, /tmp/firmware.bin]

  - name: dmidecode Test
    steps:
      - cmd: hwaas
        name: Power on DUT
        options:
          timeout: 20m
        parameters:
          <<: *hwaas_parameter
          command: power
          args: ["on"]

      - cmd: ping
        name: Wait for SSH service
        options:
          timeout: 2m
        parameters:
          host: "[[.Host]]"

      - cmd: cmd
        name: dmidecode
        transport: *transport
        parameters:
          executable: dmidecode

  - name: Post-Requirement
    steps:
      - cmd: hwaas
        name: Write backup image to flash
        options:
          timeout: 60m
        parameters:
          <<: *hwaas_parameter
          command: flash
          args: [write, /tmp/oldfirmware.bin]
