name: Build Prodrive Hermes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-hermes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
    - name: Build Prodrive Hermes Board
      uses: ./.github/actions/buildx86
      with:
        config: firmwareci/config.prodrive_hermes.edk2
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: coreboot.rom
        path: ./build/coreboot.rom
    - uses: docker://firmwareci/action:v3.0
      with:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        WORKFLOW_ID:   01J0MXWP8B1NQVMATY60JSWW4B
        COMMIT_HASH: ${{ github.sha }}
        URI: ./build/coreboot.rom
      if: github.event_name != 'pull_request'
