name: Build Prodrive Hermes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-hermes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
    - name: Build Prodrive Hermes Board
      uses: ./.github/actions/buildx86
      with:
        config: firmwareci/config.prodrive_hermes.edk2
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: coreboot.rom
        path: ./build/coreboot.rom
    - uses: docker://firmwareci/action:v4.0
      with:
        TOKEN: ${{ secrets.FWCI_TOKEN }}
        WORKFLOW_ID:   01J0MXWP8B1NQVMATY60JSWW4B
        COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
        URI: ./build/coreboot.rom
        API: "https://api.firmwareci.9esec.dev:8444"
