name: Build Prodrive Hermes

on:
    push:
        branches:
            - prodrive/hermes

jobs:
    build-hermes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.ACCESS_TOKEN }}
                submodules: recursive
            - name: Build Prodrive Hermes Board
              uses: ./.github/actions/buildx86
              with:
                config: firmwareci/config.prodrive_hermes.edk2
                upload-artifacts: false
                token: ${{ secrets.ACCESS_TOKEN }}
            - uses: docker://firmwareci/uploader:v1.1
              with:
                EMAIL: ${{ secrets.EMAIL }}
                PASSWORD: ${{ secrets.PASSWORD }}
        
                PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
                COMMIT_HASH: ${{ github.sha }}
        
                BINARY_PATH: ./build/coreboot.rom
                
                PROTOCOL: local
                API: https://api.firmwareci.9esec.dev:8443  