name: Sync Fork

on:
  schedule:
    - cron: '* */4 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: coreboot
          base: main
          head: main
          ignore_fail: true
          merge_method: merge
